### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oofgangcrypin** [iBLiSSINonYT/survivio-plus#1]
Everytime I join in, it lasts about a second then kicks me out, saying "Host has closed the session"
or something like that, it was working yesterday but not anymore

**Comment by iBLiSSINonYT** [comment]
Turn off obstacle transparency. 

This video will show you how if it kicks you out immediately.

[https://www.youtube.com/watch?v=pEEa6b3oXjA](url)

In the future, transparency fixes are on my to-do list.

**Comment by oofgangcrypin** [comment]
Now it’s loading but none of the mods are working
