### ISSUE TITLE
aint no issue - lima

### ISSUE THREAD

**Issue by ScripterLima** [iBLiSSINonYT/survivio-plus#8]
ma dud its worth 10$ but this is for the peeps that keep saying upload the free one [ JUST FUCKING PAY FOR IT U SKIDS ALWAYS WANTING FREE SHIT NOT EVERYTHING IN LIFE IS FREE ] Thank u :D

**Comment by humphreygaming** [comment]
uh, no?

**Comment by IceHacks** [comment]
"NOT EVERYTHING IN LIFE IS FREE"

https://github.com/IceHacks/SurvivCheatInjector hehehe
